version: "3.9"

services:
  db:
    container_name: db
    ports:
      - "5432:5432"
    env_file:
      - .env
    image: postgres:15-alpine3.17

  app:
    container_name: app
    image: svmilahin/hw26_app:$GITHUB_REF_NAME-$GITHUB_RUN_ID

