version: "3.9"

services:
  db:
    container_name: db
    ports:
      - "5432:5432"
    env_file:
      - .env
    image: postgres:15-alpine3.17
    volumes:
      - ./data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgroot
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_NAME=postgres


  app:
    container_name: app
    build: ./

    ports:
      - "5000:5000"
    volumes:
      - ".:/app"
    depends_on:
      - db
    command: gunicorn --bind 0.0.0.0:5000 run:app
