version: "3.9"

services:
  db:
    container_name: db
    ports:
      - "5432:5432"

    image: postgres:15-alpine3.17
    environment:
      POSTGRES_NAME: postgres
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgroot
      POSTGRES_HOST_AUTH_METHOD: trust

  app:
    container_name: app
    image: svmilahin/hw26_app:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    ports:
      - "5000:80"
    command: flask run -h 0.0.0.0 -p 5000
    restart: always

