name: Build and deploy workflow
on: [push]
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: clone code
        uses: actions/checkout@v3
      - name: docker build
        run: docker build -t svmilahin/skypro_hw26_app:$GITHUB_REF_NAME-$GITHUB_RUN_ID .
      - name: docker login
        run: echo ${{ secret.DOCKER_TOKEN }} | docker login -u ${{ secret.DOCKER_USERNAME }} --password-stdin
      - name: docker push
        run: docker push svmilakhin/skypro_hw26_app:$GITHUB_REF_NAME-$GITHUB_RUN_ID
